POST http://localhost:8080/v1/players
Content-Type: application/json

{
  "name": "Luram Archanjo"
}

###

PATCH http://localhost:8080/v1/players/bc54b875-5b6b-4ec7-8743-114b765ff333
Content-Type: application/json

{
  "score": 1
}

###

GET http://localhost:8080/v1/players
Content-Type: application/json

###